class BookGenres {
  static const List<String> genres = [
    // Ficção Literária
    "Romance",
    "Conto",
    "Drama",
    "Literatura Clássica",
    "Ficção Contemporânea",
    "Ficção Histórica",
    "Ficção Experimental",

    // Ficção de Gênero
    "Ficção Científica",
    "Fantasia",
    "Horror/Terror",
    "Suspense/Thriller",
    "Romance Paranormal",
    "Mistério/Detetive",
    "Crime/Policial",
    "Romance Histórico",
    "Chick Lit",
    "Comédia Romântica",
    "Distopia",
    "Utopia",
    "Space Opera",
    "Cyberpunk",
    "Steampunk",
    "Western",
    "Ficção Pós-apocalíptica",

    // Ficção Juvenil/YA (Young Adult)
    "YA Fantasia",
    "YA Distopia",
    "YA Contemporâneo",
    "YA Mistério",
    "YA Romance",
    "YA Aventura",
    "YA Terror",

    // Ficção Infantil
    "Livros Ilustrados",
    "Fábulas",
    "Contos de Fadas",
    "Fantasia Infantil",
    "Aventura Infantil",
    "Mistério Infantil",
    "Ficção Científica Infantil",
    "Horror Infantil",

    // Não Ficção
    "Biografia/Autobiografia",
    "Memórias",
    "História",
    "Ciência",
    "Psicologia",
    "Filosofia",
    "Religião/Espiritualidade",
    "Autoajuda/Desenvolvimento Pessoal",
    "Política",
    "Economia",
    "Negócios e Finanças",
    "Sociologia",
    "Antropologia",
    "Educação",
    "Jornalismo e Reportagens",
    "Viagem",
    "Saúde e Bem-estar",
    "Esportes",
    "Culinária/Gastronomia",
    "Arte",
    "Música",
    "Cinema e Televisão",
    "Design",
    "Arquitetura",
    "Guia e Referência",
    "Ensaio Fotográfico",
    "Relato de Viagem",

    // Poesia e Teatro
    "Poesia Clássica",
    "Poesia Contemporânea",
    "Teatro Clássico",
    "Teatro Moderno",
    "Monólogos",
    "Peças Curtas",

    // Outros Gêneros Específicos
    "Ensaios",
    "Antologias",
    "Contos Curtos",
    "Literatura Epistolar",
    "Satírica",
    "Realismo Mágico",
    "Narrativa Documental",
    "Ficção Flash (Microcontos)",
    "Light Novel",
    "Mangá/Quadrinhos",
    "Graphic Novel",
    "Livro-jogo",
    "Transmídia/Multimídia"
  ];
}